name: Foundry setup
description: A generalized foundry setup doing common things, like building and emitting a version.
inputs:
  ZKSYNC:
    description: "If tests should use zksync profile"
    default: "false"
  FOUNDRY_VERSION:
    description: "The version of Foundry to install"
    options:
      - "nightly"
      - "stable"
    default: "nightly"

runs:
  using: "composite"
  steps:
    - name: Make empty dir content tmp dir
      shell: bash
      run: mkdir -p /tmp/content

    - name: Install Foundry
      if: ${{ inputs.zksync != 'true' }}
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ inputs.FOUNDRY_VERSION }}

    - name: Install Foundry zksync
      if: ${{ inputs.zksync == 'true' }}
      uses: bgd-labs/foundry-zksync-toolchain@340cea9a42119d9a77a6bb0a8236d4311582b709
      with:
        version: nightly

    - name: Run Forge version
      shell: bash
      run: |
        forge --version
        forge cache ls
      id: version
