name: Foundry setup
description: A generalized foundry setup doing common things, like building and emitting a version.
inputs:
  ZKSYNC:
    description: "If tests should use zksync profile"
    default: "false"
  FOUNDRY_VERSION:
    description: "The version of Foundry to install"
    options:
      - "nightly"
      - "stable"
    default: "nightly"

runs:
  using: "composite"
  steps:
    - name: Make empty dir content tmp dir
      shell: bash
      run: mkdir -p /tmp/content

    - name: Install Foundry
      if: ${{ inputs.zksync != 'true' }}
      uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10
      with:
        version: ${{ inputs.FOUNDRY_VERSION }}

    - name: Install Foundry zksync
      if: ${{ inputs.zksync == 'true' }}
      uses: bgd-labs/foundry-zksync-toolchain@f7fa458f4f0d94dfdeb1759e7842e3b8e1c97a8d
      with:
        version: nightly

    - name: Run Forge version
      shell: bash
      run: |
        forge --version
        forge cache ls
      id: version
