name: Foundry gas report
description: Compares gas on default branch against the pr

runs:
  using: "composite"
  steps:
    - name: Cache Restore
      id: cache
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # pin@v4
      with:
        path: cache
        key: ${{ runner.os }}-bgd-foundry-gas-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-bgd-foundry-gas-
          ${{ runner.os }}-

    - name: Create backup
      if: steps.cache.outputs.cache-matched-key != ''
      shell: bash
      run: |
        cd cache
        ls -l
        cd ..
        cp cache/gas.json cache/gas.backup.json || :

    # required
    - name: Build
      shell: bash
      run: forge build

    - name: Gas report
      shell: bash
      run: forge test --fuzz-runs 1 --gas-report --json > cache/gas.json

    - uses: bgd-labs/action-foundry-gas-diff@main
      id: gas
      with:
        # The path to the first contract to compare
        ROOT_REPORT_PATH: "cache/gas.backup.json"
        # The path to the second contract to compare
        REPORT_PATH: "cache/gas.json"
        ignoreUnchanged: "true"

    - name: Prepare comment
      shell: bash
      run: |
        printf ":fuelpump: **Gas report**\n\n" > /tmp/template.md
        printf '%s' "${{ steps.gas.outputs.gas-report }}" >> /tmp/template.md

    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "Gas report"

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: /tmp/template.md
        edit-mode: replace

    - name: Cache Save
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # pin@v4
      with:
        path: cache
        key: ${{ runner.os }}-bgd-foundry-gas-${{ github.sha }}
