name: Foundry gas report
description: Compares gas on default branch against the pr

runs:
  using: "composite"
  steps:
    - uses: bgd-labs/action-foundry-gas-diff@main
      id: gas

    - name: Prepare comment
      shell: bash
      run: |
        printf '%s' "${{ steps.gas.outputs.report }}" > /tmp/content/gas.txt