name: "Foundry size"
description: "Testing foundry contract sizes"

runs:
  using: "composite"
  steps:
    - name: Download previous sizes report
      if: ${{ github.event_name == 'pull_request' }}
      uses: dawidd6/action-download-artifact@72aaadce3bc708349fc665eee3785cbb1b6e51d0 # v3.1.1
      with:
        branch: ${{ github.base_ref }}
        name: sizes-report
        if_no_artifact_found: warn
        path: /tmp/
        check_artifacts: true

    - name: Generate Report
      shell: bash
      run: |
        if [ -f /tmp/sizes.json ]; then
          mv /tmp/sizes.json /tmp/sizes.base.json
        fi
        forge build --sizes --json > /tmp/sizes.json || echo "Sizes report failed"
        ## if the base file doesn't exist, we compare against itself
        if [ ! -f /tmp/sizes.base.json ]; then
          cp /tmp/sizes.json /tmp/sizes.base.json
        fi

    - name: Upload sizes report
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
      if: always()
      with:
        name: sizes-report
        path: /tmp/sizes.json

    - name: Compare reports
      uses: bgd-labs/action-forge-sizes@main
      if: always() && github.event_name == 'pull_request'
      id: sizes
      with:
        comment: false
        base-report-path: /tmp/sizes.base.json
        report-path: /tmp/sizes.json

    - name: Prepare reports comment
      if: always() && github.event_name == 'pull_request'
      shell: bash
      run: |
        printf '%s' "${{ steps.sizes.outputs.report }}" > /tmp/content/forge-sizes.txt
