name: "Foundry test"
description: "Testing foundry repos"
inputs:
  MODE:
    description: "Test ALL or CHANGED tests only"
    default: "ALL"
  # this will be a string even if type is boolean
  # github actions bug from 2021 https://github.com/actions/runner/issues/2238
  ZKSYNC:
    description: "If tests should use zksync profile"
    default: "false"
  FORGE_SNAPSHOT_CHECK:
    description: "If gas snapshot check should be run"
    default: "false"

outputs:
  testStatus:
    description: "The test result"
    value: ${{ steps.all.outputs.testStatus || steps.changed.outputs.testStatus || 0 }}

runs:
  using: "composite"
  steps:
    # in all mode we simply run all tests
    - name: Test All
      id: all
      if: ${{ inputs.MODE == 'ALL' }}
      shell: bash
      run: |
        ${{ inputs.ZKSYNC == 'true' && 'FOUNDRY_PROFILE=zksync' || '' }} forge test ${{ inputs.zksync == 'true' && '--zksync' || ''}} -vv | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' | tee /tmp/foundry_test
        status=${PIPESTATUS[0]}
        echo "testStatus=$status" >> $GITHUB_OUTPUT
        printf '<details><summary>%s <strong>Test Results ${{ inputs.zksync == 'true' && 'zksync' || '' }}</strong></summary>\n\n```shell\n%s\n```\n</details>' "$([ $status -eq 0 ] && echo ":rainbow:" || echo ":finnadie::x:")" "$(cat /tmp/foundry_test)" >> /tmp/content/test.txt
      env:
        FORGE_SNAPSHOT_CHECK: ${{ inputs.FORGE_SNAPSHOT_CHECK }}

    # in changed mode we need to get all changed test(*.t.sol) files and run tests on them specifically
    - name: Get all changed *.t.sol file(s)
      if: ${{ inputs.MODE == 'CHANGED' }}
      id: changed-files
      uses: tj-actions/changed-files@f79274f27befa7e1bf6d5eb1c4964c0f65cea226
      with:
        json: true
        write_output_files: true
        files: |
          ${{ inputs.ZKSYNC == 'true' && 'zksync' || 'src' }}/**/*.t.sol

    - name: Run step if any *.md file(s) change
      if: ${{ inputs.MODE == 'CHANGED' && steps.changed-files.outputs.any_changed == 'true'}}
      shell: bash
      run: |
        cat .github/outputs/all_changed_files.json

    - name: Test Changed
      id: changed
      if: ${{ inputs.MODE == 'CHANGED' && steps.changed-files.outputs.any_changed == 'true' }}
      shell: bash
      run: |
        json_array=($(jq -r '.[]' ".github/outputs/all_changed_files.json"))
        status=0

        # github sets -e automatically which breaks the pipe
        set +e

        for i in "${json_array[@]}"
        do
          ${{ inputs.ZKSYNC == 'true' && 'FOUNDRY_PROFILE=zksync' || '' }} forge test ${{ inputs.zksync == 'true' && '--zksync' || ''}} --match-path $i -vv | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' | tee -a /tmp/foundry_test
          if [ ${PIPESTATUS[0]} -eq 1 ]
          then
            status=1
          fi
        done
        echo "testStatus=$status" >> $GITHUB_OUTPUT
        printf '<details><summary>%s<strong>Test Results</strong></summary>\n%s</details>' "$([ $status -eq 0 ] && echo ":rainbow:" || echo ":finnadie::x:")" "$(cat /tmp/foundry_test)" >> /tmp/content/test.txt
        exit 0
      env:
        FORGE_SNAPSHOT_CHECK: ${{ inputs.FORGE_SNAPSHOT_CHECK }}
