name: "Foundry test"
description: "Testing foundry repos"
inputs:
  MODE:
    description: "Test ALL or CHANGED tests only"
    default: "ALL"

runs:
  using: "composite"
  steps:
    - name: Test All
      if: ${{ inputs.MODE == 'ALL' }}
      shell: bash
      run: |
        forge test -vv | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' | tee /tmp/foundry_test
        echo "testStatus=${PIPESTATUS[0]}" >> $GITHUB_ENV

    - name: Get all changed *.t.sol file(s)
      if: ${{ inputs.MODE == 'CHANGED' }}
      id: changed-files
      uses: tj-actions/changed-files@f79274f27befa7e1bf6d5eb1c4964c0f65cea226
      with:
        json: true
        write_output_files: true
        files: |
          **/*.t.sol

    - name: Run step if any *.md file(s) change
      if: ${{ inputs.MODE == 'CHANGED' && steps.changed-files.outputs.any_changed == 'true'}}
      shell: bash
      run: |
        cat .github/outputs/all_changed_files.json

    - name: Test Changed
      if: ${{ inputs.MODE == 'CHANGED' && steps.changed-files.outputs.any_changed == 'true' }}
      shell: bash
      run: |
        json_array=($(jq -r '.[]' ".github/outputs/all_changed_files.json"))
        status=0

        # github sets -e automatically which breaks the pipe
        set +e

        for i in "${json_array[@]}"
        do
          forge test --match-path $i -vv | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' | tee -a /tmp/foundry_test
          if [ ${PIPESTATUS[0]} -eq 1 ]
          then
            status=1
          fi
        done
        echo "testStatus=$status" >> $GITHUB_ENV
        exit 0
