# Test seup used to test the ci within this repository
name: Foundry test

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/foundry-test.yml
    with:
      MODE: "CHANGED"
  test-zksync:
    uses: ./.github/workflows/foundry-test.yml
    with:
      MODE: "CHANGED"
      zksync: true
  release:
    needs: [test]
    uses: ./.github/workflows/release.yml
