# By calling this ci via `workflow_call` from another ci it has permissions to comment on prs from forks
name: comment-pr-results

on:
  workflow_call:

jobs:
  comment:
    name: Comment Bot
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/download-artifact/issues/3 official actions doesn't support downloads from different workflows
      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          name: pr_number
          path: pr/pr_number.txt

      - name: Read pr number
        id: get_pr_number
        run: echo "pr_number=$(cat pr/pr_number.txt)" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v3dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          name: ${{ steps.get_pr_number.outputs.pr_number }}
          path: /tmp/template.md

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        if: |
          github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Foundry report

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@c6c9a1a66007646a28c153e2a8580a5bad27bcfa
        if: |
          github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          token: ${{ github.token }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: /tmp/template.md
          edit-mode: replace
