name: foundry test

on:
  workflow_call:
    inputs:
      mode:
        default: "ALL"
        type: "string"
      compareGas:
        default: true
        type: boolean
      compareLcov:
        default: true
        type: boolean
      compareSize:
        default: true
        type: boolean
    secrets:
      ALCHEMY_API_KEY:
        required: false
      READ_ONLY_PAT:
        required: false
        description: "If supplied PAT will be used for git checkout(relevant for private repos)"
      QUICKNODE_TOKEN:
        required: false
      QUICKNODE_ENDPOINT_NAME:
        required: false

jobs:
  test:
    name: Foundry build n test
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci
    steps:
      ### Setup ###
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.READ_ONLY_PAT || github.token }}

      - uses: bgd-labs/action-rpc-env@f56d90aa2505822c6c81a9242625551b68b4859f
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          QUICKNODE_TOKEN: ${{ secrets.QUICKNODE_TOKEN }}
          QUICKNODE_ENDPOINT_NAME: ${{ secrets.QUICKNODE_ENDPOINT_NAME }}

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Run Foundry setup
        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main

      ### Ensure contract size is not exceeded ###
      - name: Run Forge size
        if: ${{ inputs.compareSize }}
        uses: bgd-labs/github-workflows/.github/actions/foundry-size@main
        continue-on-error: true

      - name: Run Gas report
        if: ${{ inputs.compareGas }}
        uses: bgd-labs/github-workflows/.github/actions/foundry-gas-report@main
        continue-on-error: true

      ### Run tests ###
      - name: Run Forge tests
        id: test
        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
        with:
          MODE: ${{ inputs.mode }}

      ### Extended reports ###
      - name: Run Lcov report
        if: ${{ inputs.compareLcov }}
        uses: bgd-labs/github-workflows/.github/actions/foundry-lcov-report@main

      - name: Upload & Trigger Comment artifact
        if: always()
        uses: bgd-labs/github-workflows/.github/actions/comment-artifact@main
        with:
          nameSuffix: "default"
