name: Test workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: .github/workflows/foundry-test.yml
  release:
    needs: [test]
    uses: .github/workflows/release.yml
